const knowledgeBase = [
    // Genel Karşılamalar
    { q: "selam", a: "Merhaba! Ben Elite AI Advisor. Size finansal stratejiler, vergi mevzuatı veya şirket yönetimi konularında nasıl yardımcı olabilirim?" },
    { q: "merhaba", a: "Merhaba! Elite Financial ekibinin akıllı asistanıyım. Finansal mühendislik ve mali danışmanlık konularındaki sorularınızı bekliyorum." },
    { q: "nasılsın", a: "Harikayım! Şirketlerin finansal yapılarını analiz etmek ve sorularınızı yanıtlamak için hazırım. Siz nasılsınız?" },

    // Vergi ve Beyanname
    { q: "KDV beyannamesi ne zaman verilir?", a: "Katma Değer Vergisi (KDV) beyannamesi, vergilendirme dönemini takip eden ayın 28. günü akşamına kadar verilir ve ödenir." },
    { q: "Gelir vergisi oranları nelerdir?", a: "2024 yılı gelir vergisi oranları %15 ile %40 arasında kademelidir. 110.000 TL'ye kadar %15, 230.000 TL'ye kadar %20, 580.000 TL'ye kadar %27, 3.000.000 TL'ye kadar %35 ve üzeri için %40 uygulanır." },
    { q: "e-Fatura zorunluluğu?", a: "2023 yılı brüt satış hasılatı 3 milyon TL ve üzeri olan mükellefler 1 Temmuz 2024 itibarıyla e-Fatura'ya geçmek zorundadır." },
    { q: "Genç girişimci istisnası?", a: "29 yaşını doldurmamış girişimciler 3 yıl boyunca kazançlarının belirli bir kısmından muaftır ve 1 yıl Bağ-Kur primi devletçe karşılanır." },
    { q: "Kurumlar vergisi oranı?", a: "2024 yılı için standart kurumlar vergisi oranı %25'tir. Ancak banka ve finans kurumları için %30, ihracatçı firmalar için %20 civarı indirimli oranlar uygulanabilir." },
    { q: "Stopaj nedir?", a: "Gelirin kaynağında kesilerek vergi dairesine ödenmesidir. Kira, serbest meslek ödemeleri ve personel maaşlarında uygulanır." },
    { q: "Damga vergisi beyannamesi?", a: "Sözleşmeler, makbuzlar ve resmi kağıtlar üzerinden alınan bir vergidir. İzleyen ayın 26. günü sonuna kadar beyan edilir." },
    { q: "Geçici vergi dönemleri?", a: "Şubat, Mayıs, Ağustos ve Kasım aylarında olmak üzere 3'er aylık dönemler halinde beyan edilir." },
    { q: "Muhtasar beyanname?", a: "Yapılan tevkifatların (stopaj) bildirildiği beyannamedir. Aylık veya 3 aylık dönemlerle verilebilir." },
    { q: "Yıllık gelir vergisi Mart?", a: "Evet, yıllık gelir vergisi beyannamesi Mart ayının sonuna kadar teslim edilir." },

    // Şirket Kuruluşu ve Yönetimi
    { q: "Anonim Şirket mi Limited mi?", a: "A.Ş. büyük ölçekli ve halka arz vizyonu olan yapılar için uygundur. L.T.D. ise daha küçük, ortaklık yapısının önemli olduğu butik işletmeler için idealdir." },
    { q: "Şirket kuruluşu ne kadar?", a: "Ortalama 2-3 iş günü içinde ticaret sicil tescili tamamlanır. Maliyetler sermaye tutarına ve meslek grubu kayıtlarına göre değişir." },
    { q: "Halka arz şartları?", a: "Kar elde etme geçmişi, minimum özkaynak tutarı ve SPK onaylı kurumsal yönetim uyumu gereklidir." },
    { q: "Konkordato süreci?", a: "Mali darboğazdaki şirketin borçlarını yapılandırarak iflastan kurtulmasını sağlayan mahkeme onaylı bir iyileştirme sürecidir." },
    { q: "Holdingleşme avantajları?", a: "Grup şirketleri arası kar transferlerinde vergi avantajı, merkezi hazine yönetimi ve risk izolasyonu sağlar." },
    { q: "Sanal ofis yasal mı?", a: "Evet, tebligat adresi olarak sanal ofis kullanımı tamamen yasaldır ve vergi dairesi yoklamasını geçer." },
    { q: "LTD ortağının sorumluluğu?", a: "Ortaklar, şirkete getirmeyi taahhüt ettikleri sermaye borcu kadar sorumludur. Ancak kamu borçlarında (vergi, SGK) payları oranında şahsi sorumlulukları vardır." },
    { q: "Anonim Şirket asgari sermaye?", a: "2024 güncel rakamı 250.000 TL'dir. Kayıtlı sermaye sisteminde bu rakam daha yüksek olabilir." },

    // İleri Düzey Finans & Mevzuat
    { q: "IFRS / TMS nedir?", a: "Uluslararası Finansal Raporlama Standartlarıdır. Şirket mali tablolarının dünya genelinde aynı dilde okunmasını sağlar." },
    { q: "Enflasyon düzeltmesi?", a: "Paranın değer kaybı nedeniyle mali tabloların reel duruma göre güncellenmesidir. 2023 sonu itibarıyla zorunlu hale gelmiştir." },
    { q: "Örtülü sermaye?", a: "Şirketin ortaklarından aldığı borcun, öz sermayesinin üç katını aşması durumudur. Aşım kısmına ait faizler kanunen kabul edilmeyen gider sayılır." },
    { q: "Transfer fiyatlandırması?", a: "İlişkili şirketler arası mal ve hizmet alımında fiyatın emsallere uygun olması gerekliliğidir; aksi halde vergi ziyaı cezası doğabilir." },
    { q: "Çifte vergilendirmeyi önleme?", a: "Türkiye'nin birçok ülke ile yaptığı anlaşmalar sayesinde, aynı kazancın iki ülkede birden vergilendirilmesinin önüne geçilir." },
    { q: "KDV iadesi nasıl alınır?", a: "İhracat veya indirimli orana tabi işlemlerden doğan KDV yükü, vergi incelemesi veya YMM raporu ile iade alınabilir." },
    { q: "Ar-Ge merkezi teşviki?", a: "Ar-Ge personelinin SGK işveren hissesi %50 indirimlidir ve yapılan harcamalar %100 oranında vergi matrahından düşülür." },
    { q: "Yatırım teşvik belgesi?", a: "Gümrük muafiyeti, KDV istisnası, vergi indirimi ve SGK prim desteği gibi avantajlar sunan Sanayi Bakanlığı belgesidir." },
    { q: "Konaklama vergisi?", a: "Otel, tatil köyü gibi tesislerde sunulan konaklama hizmeti üzerinden %2 oranında alınan bir vergidir." },
    { q: "Dijital hizmet vergisi?", a: "Dijital ortamdaki reklam hizmetleri ve içerik satışlarından elde edilen hasılat üzerinden %7.5 oranında alınan vergidir." },

    // İşletme ve İK
    { q: "Bordrolama outsource?", a: "Gizlilik, maliyet tasarrufu ve operasyonel hataların sıfırlanması için İK süreçlerinin profesyonel firmalara devredilmesidir." },
    { q: "Kıdem tazminatı tavanı?", a: "Her yıl Ocak ve Temmuz aylarında güncellenir. 2024 Temmuz itibarıyla güncel tavan rakamı yetkililerimizce bildirilecektir." },
    { q: "SGK 5 puanlık indirim?", a: "Primlerini düzenli ödeyen işverenlere sağlanan %5 oranındaki hazine desteğidir." },
    { q: "İşsizlik sigortası fonu?", a: "İşçi payı %1, işveren payı %2 ve devlet payı %1 olacak şekilde kesilen fondur." },
    { q: "Asgari geçim indirimi (AGI)?", a: "Asgari ücretin vergi dışı bırakılmasıyla birlikte AGI uygulaması kalkmıştır." },
    { q: "İşe alım teşvikleri?", a: "6111 ve 7103 sayılı kanunlar gibi istihdamı artıran firmalara sağlanan prim ve vergi destekleridir." },

    // Denetim ve Raporlama
    { q: "Bağımsız denetim?", a: "Şirketlerin finansal verilerinin dışarıdan bağımsız bir kuruluşça doğruluğunun ve şeffaflığının onaylanması sürecidir." },
    { q: "YMM tam tasdik?", a: "Yeminli Mali Müşavirlerin şirketin vergi beyannamelerinin doğruluğunu onaylaması sürecidir; vergi inceleme riskini azaltır." },
    { q: "İç denetim?", a: "Şirket içi süreçlerin verimliliğini ve risk yönetimini ölçen departman veya hizmet bazlı kontrol yapısıdır." },
    { q: "Maliyet muhasebesi?", a: "Üretilen birim başına düşen maliyeti hesaplayarak fiyatlandırma ve karlılık analizi yapmaya yarayan uzmanlık alanıdır." },

    // Rastgele Sorular (Keyword ekleme)
    { q: "fatura", a: "E-Fatura, e-Arşiv ve e-İrsaliye gibi süreçlerde yasal düzenlemelere uyum hayati önem taşır. Hatalı fatura usulsüzlük cezasına yol açabilir." },
    { q: "ceza", a: "Vergi ziyaı cezası, usulsüzlük cezası veya gecikme faizi gibi durumlarda uzlaşma veya yapılandırma yolları denenebilir." },
    { q: "KDV iadesi türleri?", a: "İhracat istisnası, indirimli oran, tam istisna kapsamındaki işlemler gibi birçok farklı iade kategorisi mevcuttur." },
    { q: "Barkod ve Marka tescili maliyetleri?", a: "Türk Patent ve Marka Kurumu harçları ve danışmanlık ücretlerini kapsar; vergi matrahından gider olarak düşülebilir." },
    // Yeni Eklenen Devasa Veri Seti
    { q: "Özel tüketim vergisi (ÖTV) nedir?", a: "Lüks tüketim, tütün, alkol, taşıt ve akaryakıt gibi belirli mallar üzerinden alınan bir vergidir." },
    { q: "E-İrsaliye geçiş şartları?", a: "2023 yılı brüt satış hasılatı 10 milyon TL ve üzeri olan mükellefler için zorunludur." },
    { q: "Zayi belgesi nedir?", a: "Yangın, deprem veya su basması gibi nedenlerle defter ve belgelerin kaybolması durumunda mahkemeden alınan belgedir." },
    { q: "Kar dağıtım stopajı oranı?", a: "Tam mükellef kurumlara yapılan kar dağıtımlarında vergi kesintisi oranı %10 olarak uygulanmaktadır." },
    { q: "Asgari kurumlar vergisi nedir?", a: "Kurumların indirim ve istisnalar düşülmeden önceki kazançları üzerinden alınan düşük oranlı bir vergi düzenlemesidir." },
    { q: "Vergi inceleme raporuna itiraz?", a: "Raporun tebliğinden itibaren ilgili komisyonlara dinlenme talebinde bulunulabilir veya doğrudan dava açılabilir." },
    { q: "Sermaye artırımı tescili?", a: "Genel kurul kararından itibaren 30 gün içinde ticaret siciline tescil ettirilmelidir." },
    { q: "Ayni sermaye konulabilir mi?", a: "Evet, gayrimenkul veya makine gibi değerler bilirkişi raporuyla sermaye olarak eklenebilir." },
    { q: "Hibe ve fonların vergilendirilmesi?", a: "TÜBİTAK veya KOSGEB gibi kurumlardan alınan geri ödemesiz destekler genellikle kurumlar vergisinden istisnadır." },
    { q: "Teknoparklarda vergi avantajı?", a: "Yazılım geliştirme ve Ar-Ge kazançları, personel gelir vergisi ve damga vergisi muafiyetleri mevcuttur." },
    { q: "İrtibat bürosu vergileri?", a: "İrtibat büroları ticari faaliyette bulunamazlar; bu nedenle kurumlar vergisi ödemezler, ancak personel stopajı öderler." },
    { q: "YMM raporu ibraz süresi?", a: "KDV iade taleplerinde genellikle beyanname tarihinden itibaren 6 ay ile 1 yıl arasında değişen süreler mevcuttur." },
    { q: "Vergi barışı kapsamında matrah artırımı?", a: "Belirli yıllar için vergi matrahını artırarak o yıllara ait vergi inceleme riskini ortadan kaldıran yasal bir imkandır." },
    { q: "VUK 359 kaçakçılık suçları?", a: "Sahte belge düzenleme veya kullanma (naylon fatura) gibi durumlarda hapis cezası öngören ağır suçlardır." },
    { q: "E-Defter berat yükleme süresi?", a: "İlgili ayı takip eden üçüncü ayın sonuna kadar GİB sistemine yüklenmelidir." },
    { q: "Sorumluluk raporu nedir?", a: "Mali müşavirin mükellefin vergi ziyaı durumunda müteselsilen sorumlu tutulabileceğini belirten rapordur." },
    { q: "Tasfiye memuru sorumluluğu?", a: "Şirket varlıklarını paraya çevirme ve borçları ödeme sürecinde yasal düzenlemelere harfiyen uymakla yükümlüdür." },
    { q: "Gayri maddi hak ödemesi stopajı?", a: "Yazılım lisansı veya marka kullanımı için yurt dışına yapılan ödemelerde genellikle %20 stopaj uygulanır." },
    { q: "Sermaye azaltımı stopajı?", a: "Özkaynaklar içindeki geçmiş yıl karlarının sermayeden çekilmesi durumunda kar dağıtımına bağlı stopaj doğabilir." },
    { q: "Yurtdışı iştirak kazancı istisnası?", a: "Yurt dışındaki iştirakinizden elde edilen temettülerin belirli şartlarla Türkiye'de vergiden muaf olmasıdır." },
    { q: "Mali tatil tarihleri?", a: "Her yıl 1-20 Temmuz arası mali tatil olup beyan ve ödeme süreleri uzatılır." },
    { q: "Defter-Beyan sistemi nedir?", a: "Küçük mükelleflerin (işletme hesabı) kayıtlarını doğrudan GİB portalı üzerinden tuttukları sistemdir." },
    { q: "Huzur hakkı vergilendirmesi?", a: "Şirket ortaklarına yönetim kurulu üyelikleri nedeniyle verilen ücretlerdir ve personel gibi vergilendirilir." },
    { q: "bağkur", a: "Şirket ortakları 4/b (Bağ-Kur) kapsamında sigortalıdır. Zamanında ödenen primler emeklilik haklarınızı garanti altına alır." },
    { q: "emeklilik", a: "EYT ve güncel mevzuat kapsamında emeklilik planlamanızı yapabilir, kıdem tazminatı yükünüzü analiz edebiliriz." },

    // EK DESTEK PAKETİ (200'E TAMAMLAMA)
    { q: "Maliye Bakanlığı özelge havuzu?", a: "GİB portalı üzerinden benzer olaylar için verilmiş özelgelere ulaşarak vergi uygulamalarında emsal kararları inceleyebilirsiniz." },
    { q: "Nakit sermaye artırımı faiz indirimi?", a: "Şirketlerin nakdi sermaye artırımları üzerinden hesaplanan faizin belirli bir kısmının kurumlar vergisi matrahından düşülmesini sağlayan bir teşviktir." },
    { q: "İştirak hissesi satış kazancı?", a: "Kurumların iştirak hisselerini en az iki yıl ellerinde tutmaları şartıyla satış kazancının %75'i vergiden istisnadır." },
    { q: "Bedelsiz sermaye artırımı?", a: "Şirket iç kaynaklarının (yedek akçeler, fonlar) sermayeye eklenerek ortaklara bedelsiz pay verilmesi işlemidir." },
    { q: "Rüçhan hakkı nedir?", a: "Mevcut ortakların sermaye artırımında yeni payları öncelikle satın alma hakkıdır." },
    { q: "Varlık barışı son durum?", a: "Yurt dışındaki veya yurt içindeki kayıt dışı varlıkların belirli bir vergi oranıyla sisteme dahil edilerek inceleme bağışıklığı kazanmasıdır." },
    { q: "E-SMM zorunluluğu?", a: "Tüm serbest meslek erbapları (mali müşavir, avukat vb.) işe başladıkları ayı takip eden tarihten itibaren e-SMM kullanmak zorundadır." },
    { q: "E-Müstahsil makbuzu?", a: "Defter tutan çiftçilerin, defter tutmayan çiftçilerden mal alırken düzenledikleri elektronik belgedir." },
    { q: "Adi ortaklık vergilemesi?", a: "Gelir ve Kurumlar vergisi yönünden ortaklık bazında değil, ortakların şahsi beyannameleri üzerinden vergilendirme yapılır." },
    { q: "Şahıs şirketi mi LTD mi?", a: "Küçük hacimli işler ve düşük risk için şahıs firması; kurumsallık ve sınırlı sorumluluk için LTD önerilir." },
    { q: "Kira stopaj oranı 2024?", a: "İşyeri kiralamalarında standart stopaj oranı %20 olarak uygulanmaktadır." },
    { q: "Geçikme zammı ve faizi farkı?", a: "Gecikme zammı vergi vadesinden sonraki ödemeler için, gecikme faizi ise tarhiyat aşamasındaki süreler için hesaplanır." },
    { q: "YMM tasdik sınırı 2024?", a: "Beyanname tasdiki ve KDV iadeleri için yıllık olarak güncellenen belirli parasal limitler mevcuttur." },
    { q: "E-Ticarette vergi muafiyeti?", a: "Evde üretilen ürünlerin internetten satışında belirli hasılat limitlerine kadar esnaf muafiyeti belgesi ile muafiyet sağlanabilir." },
    { q: "İstisna ve Muafiyet farkı?", a: "İstisna verginin konusuna giren bir kazancın dışarıda bırakılması; muafiyet ise bir mükellef grubunun vergi dışı bırakılmasıdır." },
    { q: "Finansal kiralama (Leasing)?", a: "Yatırım mallarının satın alınması yerine kira ödeyerek kullanım hakkının elde edilmesi ve dönem sonunda mülkiyetinin devri sürecidir." },
    { q: "Faktoring işlemleri muhasebesi?", a: "Alacakların temliği ve finansmanı işlemlerinin özel hesap planı kurallarına göre kaydedilmesidir." },
    { q: "Gider kısıtlaması (Binek Araç)?", a: "Binek araç giderlerinin (yakıt, bakım, kiralama) sadece %70'inin gider kabul edilmesi kuralıdır." },
    { q: "Binek araç amortisman sınırı?", a: "Her yıl güncellenen amortisman ve gider kısıtlaması limitleri mevcuttur; limit aşan kısımlar KKEG yazılır." },
    { q: "KKEG (Kanunen Kabul Edilmeyen Gider)?", a: "Ticari kazançtan düşülen ancak vergi matrahı hesaplanırken geri eklenmesi gereken gider türleridir." },
    { q: "Net aktif değeri?", a: "Şirketin tüm varlıklarından borçlarının düşülmesiyle elde edilen değerdir." },
    { q: "EBITDA (FAVÖK) nedir?", a: "Faiz, Amortisman ve Vergi Öncesi Kar; operasyonel verimliliği ölçen en temel metriktir." },
    { q: "Nakit akım tablosu?", a: "İşletmenin dönem içindeki nakit giriş ve çıkışlarını faaliyet, yatırım ve finansman bazında gösteren tablodur." },
    { q: "Cari oran ideali?", a: "Dönen varlıkların kısa vadeli borçlara oranıdır; genellikle 1.5 - 2.0 arası ideal kabul edilir." },
    { q: "Asit-test oranı?", a: "Stoklar hariç dönen varlıkların kısa vadeli borçları karşılama gücüdür; 1.0 ve üzeri güvenli kabul edilir." },
    { q: "Yönetim kurulu huzur hakkı?", a: "Yönetim kurulu üyelerine toplantı başına veya aylık olarak ödenen ücrettir; stopaja tabidir." },
    { q: "Bağımsız üye zorunluluğu?", a: "Halka açık şirketlerde kurumsal yönetim ilkeleri gereği belirli sayıda bağımsız yönetim kurulu üyesi bulunmalıdır." },
    { q: "Nevi değişikliği?", a: "Bir şirketin hukuki türünün değişmesidir (örneğin LTD'den AŞ'ye geçiş); külli halefiyet prensibi uygulanır." },
    { q: "Şirket birleşmesi vergili mi?", a: "KVK 19. maddesine göre yapılan 'devir' niteliğindeki birleşmeler vergisiz olarak gerçekleştirilebilir." },
    { q: "Kısmi bölünme nedir?", a: "Şirketin aktifindeki bir üretim tesisinin veya gayrimenkulün yeni kurulacak veya mevcut bir şirkete ayni sermaye olarak konulmasıdır." },
    { q: "Tasfiye dönemi ne kadar?", a: "Alacaklılara çağrı ilanından itibaren en az 3 ay süren bir bekleme ve borç ödeme dönemidir." },
    { q: "Sicil tasdiknamesi?", a: "Ticaret sicilinden alınan, şirketin güncel bilgilerini ve yetkililerini gösteren resmi belgedir." },
    { q: "Mersis no nedir?", a: "Merkezi Sicil Kayıt Sistemi numarasıdır; şirketin tekil kimlik numarasıdır." },
    { q: "İmza sirküleri geçerlilik süresi?", a: "Genellikle yönetim kurulu görev süresiyle sınırlıdır veya sirkülerde belirtilen süre kadardır." },
    { q: "Tek ortaklı şirket?", a: "Hem LTD hem de AŞ yapıları tek ortakla kurulabilir veya tek ortağa düşebilir." },
    { q: "Sanal para kazancı vergisi?", a: "Henüz net bir yasal düzenleme olmamakla birlikte, ticari kazanç hükümlerine göre vergilendirilmesi yönünde görüşler bulunmaktadır." },
    { q: "Yatırım fonu katılma belgesi?", a: "Şirketlerin nakitlerini değerlendirdikleri fonların vergilendirilmesi türüne göre (A/B tipi) stopaj avantajları sunar." },
    { q: "Kurye şirketlerinde vergi?", a: "Şahıs şirketi veya esnaf muafiyeti kapsamında esnek modeller mevcuttur; genellikle motokuryeler için özel vergi düzenlemeleri vardır." },
    { q: "Influencer vergisi?", a: "Sosyal içerik üreticileri için getirilen istisna kapsamında, belirli gelir sınırına kadar banka kesintisi (%15) ile vergilendirme yapılır." },
    { q: "E-İhracat teşviki?", a: "Mikro ihracat kapsamında yapılan satışlarda kazancın yarısına varan vergi indirimleri mevcuttur." },
    { q: "Yurtdışı yazılım ihracı istisnası?", a: "Türkiye'den yurt dışındaki müşterilere verilen yazılım, tasarım vb. hizmetlerden elde edilen kazancın %80'i vergiden istisnadır." },
    { q: "KDV tevkifatı kimlere yapılır?", a: "Belirlenmiş alıcılar (kamu kurumları, halka açık şirketler vb.) tarafından belirli hizmet alımlarında yapılır." },
    { q: "İndirimli oranlı KDV iadesi?", a: "%1 veya %10 KDV ile mal satıp %20 ile girdi alan firmaların (örneğin gıda, tekstil) iade talepleridir." },
    { q: "Yüklenilen KDV nedir?", a: "Bir malın bünyesine giren ve iadeye konu edilebilecek olan alış KDV'sidir." },
    { q: "Devreden KDV'nin iadesi?", a: "Genel kural olarak devreden KDV iade alınmaz, ancak istisna kapsamındaki işlemlerde iade yolu açılır." },
    { q: "Özel fatura (Tax Free)?", a: "Yurt dışında ikamet edenlere yapılan satışlarda KDV iadesi imkanı tanıyan fatura türüdür." },
    { q: "Yolcu beraberi eşya iadesi?", a: "Turistlerin Türkiye'den aldıkları ürünlerin KDV'sini gümrükten çıkarken geri almaları sürecidir." },
    { q: "Amortisman listesi güncelleme?", a: "Varlıkların faydalı ömürleri GİB tarafından yayımlanan güncel listelere göre belirlenir." },
    { q: "Hızlandırılmış amortisman?", a: "Varlığın değerinin ilk yıllarda daha yüksek oranda giderleştirilmesini sağlayan azalan bakiyeler yöntemidir." },
    { q: "Maliyet artış fonu?", a: "Enflasyon düzeltmesi öncesi dönemlerde kullanılan, duran varlıkların değer artışlarının kaydedildiği pasif hesaptır." },
    { q: "Kar yedekleri nelerdir?", a: "Yasal yedekler, statü yedekleri ve olağanüstü yedekler gibi kar üzerinden ayrılan fonlardır." },
    { q: "Sermaye yedeği nedir?", a: "Emisyon primi gibi kar dışı kaynaklardan oluşan özkaynak kalemleridir." },
    { q: "Emisyon primi istisnası?", a: "Anonim şirketlerin hisse senetlerini nominal değerin üzerinde satmalarından doğan kazancın vergiden istisna olmasıdır." },
    { q: "Bedelli sermaye artırımı rüçhan?", a: "Ortakların nakit koyarak yeni pay alma hakkını kullanması sürecidir." },
    { q: "AŞ Genel Kurul zamanı?", a: "Hesap döneminin bitişinden itibaren 3 ay içinde (Genellikle Mart sonuna kadar) olağan genel kurul yapılmalıdır." },
    { q: "Yönetim Kurulu ibra edilmesi?", a: "Genel kurulun, yönetim kurulunun geçmiş yıl faaliyetlerini onaylayarak sorumluluklarını kaldırmasıdır." },
    { q: "Pay defteri zorunluluğu?", a: "Ciltli ve sayfaları müteselsil numaralı olması gereken, ortaklık paylarının kaydedildiği resmi defterdir." },
    { q: "Yönetim kurulu karar defteri?", a: "Alınan kararların yapıştırıldığı ve her yıl kapanış tasdiğine tabi olan defterdir." },
    { q: "Kapanış tasdiki hangi defterlere yapılır?", a: "Yevmiye defteri ve Yönetim Kurulu karar defteri için yasal süresinde kapanış tasdiki zorunludur." },
    { q: "Ara tasdik nedir?", a: "Sayfaları biten defterlerin veya yıl sonunda yeni dönem için yapılan onay işlemidir." },
    { q: "Vergi levhası bulundurma?", a: "İş yerinde fiziki olarak asma zorunluluğu kalkmış ancak elektronik ortamda sorgulanabilir durumda olması şarttır." },
    { q: "Yoklama fişi nedir?", a: "Vergi dairesinin yerinde tespit yaptığı durumu belgeleyen resmi tutanaktır." },
    { q: "Siz kimsiniz?", a: "Ben Elite Strategy bünyesinde geliştirilmiş, 200'den fazla teknik konuya hakim dijital bir finans asistanıyım." },
    { q: "Hangi konularda uzmansınız?", a: "Vergi hukuku, ticaret kanunu, maliyet muhasebesi, IFRS raporlama ve stratejik finansal yönetim temel uzmanlık alanlarım." },
    { q: "Canlı bir danışmanla görüşebilir miyim?", a: "Tabii ki! AI ile çözemediğiniz karmaşık durumlar için bilet (ticket) oluşturabilir veya iletişim bilgilerimizden bize ulaşabilirsiniz." },
    { q: "İş ortaklıkları (Joint Venture) vergisi?", a: "Kurumlar vergisi mükellefi olarak mükellefiyet tesis ettirebilir veya ortakların payına düşen kazanç üzerinden vergileme yapılabilir." },
    { q: "Adi komandit şirket?", a: "Bazı ortakların sınırsız, bazılarının sadece koydukları sermaye kadar sorumlu olduğu bir şirket türüdür." },
    { q: "Şube açılışı maliyeti?", a: "Ticaret sicil harçları ve ilan bedellerini kapsar; merkez ve şube işlemleri artık Mersis üzerinden yürütülür." },
    { q: "Temsil ve ağırlama giderleri?", a: "İşle ilgili olması şartıyla müşteri ağırlama, yemek ve konaklama giderleri makul ölçülerde gider yazılabilir." },
    { q: "Finansman gideri kısıtlaması aşımı?", a: "Aşan kısmın %10'u Kanunen Kabul Edilmeyen Gider (KKEG) olarak matraha eklenir." },
    { q: "Hesap dönemi değişikliği?", a: "Takvim yılından farklı bir hesap dönemi kullanmak için Hazine ve Maliye Bakanlığı'ndan izin alınmalıdır." },
    { q: "İz bedeli nedir?", a: "Değeri tamamen itfa olmuş ancak hala kullanılan varlıkların muhasebede 1 kuruş gibi sembolik bir değerle takip edilmesidir." },
    { q: "Yenileme fonu?", a: "Satılan duran varlığın yerine yenisi alınacaksa, satış karının 3 yıl boyunca vergilenmeden bir fonda tutulabilmesidir." },
    { q: "VUK 371 pişmanlık indirimi?", a: "Vergi ziyaı cezasının %100'ünün kaldırılmasını sağlayan, vergi dairesine kendiliğinden yapılan bildirimdir." },
    { q: "Tarhiyat öncesi uzlaşma?", a: "İnceleme elemanı tarafından rapor yazılmadan önce, vergi ve ceza tutarları üzerinde pazarlık yapılması sürecidir." },
    { q: "Vergi dairesi değişikliği?", a: "Adres değişikliği veya vergi türü değişikliği durumunda ticaret sicil tescili ile birlikte sistem üzerinden otomatik güncellenir." },
    { q: "E-Arşiv fatura limiti 2024?", a: "Vergi mükelleflerine 6.900 TL, olmayanlara 50.000 TL üzerindeki satışlarda e-Arşiv fatura düzenleme zorunluluğu vardır." },
    { q: "Serbest bölge KDV istisnası?", a: "Serbest bölgedeki firmalara Türkiye'den yapılan satışlar ihracat sayıldığı için KDV'den istisnadır." },
    { q: "Dahilde İşleme İzin Belgesi (DİİB)?", a: "İhraç edilecek ürünlerin üretiminde kullanılacak ham maddelerin gümrük vergisi ve KDV ödemeden ithal edilmesini sağlar." },
    { q: "Hariçte İşleme Rejimi?", a: "Serbest dolaşımdaki malların işlenmek üzere yurt dışına gönderilip, tekrar ithalatında gümrük kolaylığı sağlanmasıdır." },
    { q: "Transit ticaret KDV'ye tabi mi?", a: "Yabancı bir ülkeden alınan malın Türkiye'ye girmeden başka bir yabancı ülkeye satılması KDV'nin konusuna girmez." },
    { q: "Yurt dışı mukimlere verilen eğitim hizmeti?", a: "%80 kazanç istisnası kapsamında değerlendirilen, döviz getirici stratejik hizmetlerden biridir." },
    { q: "Sağlık turizmi vergi teşviği?", a: "Uluslararası sağlık turizmi yetki belgesine sahip kurumların sunduğu hizmetlerden elde edilen kazancın büyük kısmı vergiden istisnadır." },
    { q: "Kosgeb işletme geliştirme desteği?", a: "Dijitalleşme, yurt dışı iş gezisi ve personel istihdamı gibi konularda verilen geri ödemesiz destek paketleridir." },
    { q: "NACE kodu değişikliği?", a: "Şirketin ana faaliyet alanının değişmesi durumunda ticaret sicili ve vergi dairesi sisteminden güncellenmesi gereken koddur." },
    { q: "Ana sözleşme değişikliği?", a: "Unvan, merkez, amaç ve konu gibi temel maddelerin genel kurul kararıyla değiştirilmesidir." },
    { q: "İmza yetkisi devri?", a: "Yönetim kurulu veya müdürlerin, belirli yetkilerini iç yönerge veya vekaletname ile başkalarına devretmesi işlemidir." },
    { q: "Münferit vs Müşterek imza?", a: "Münferit tek başına, müşterek ise en az iki yetkilinin birlikte imza atması zorunluluğunu ifade eder." },
    { q: "Hazirun cetveli nedir?", a: "Genel kurul toplantısına katılan pay sahiplerini ve temsilcilerini gösteren imzalı listedir." },
    { q: "Yönetim kurulu faaliyet raporu?", a: "Şirketin o yıla ait operasyonel ve finansal performansını özetleyen resmi rapordur." },
    { q: "Tüzel kişi yönetim kurulu üyesi?", a: "Bir şirket başka bir şirketin yönetim kuruluna seçilebilir; ancak bu durumda bir gerçek kişiyi temsilci olarak atamalıdır." },
    { q: "İç yönerge nedir?", a: "Şirket içi hiyerarşiyi, yetki devirlerini ve operasyonel kuralları belirleyen tescile tabi belgedir." },
    { q: "Şirket web sitesi zorunluluğu?", a: "Bağımsız denetime tabi şirketlerin, belirli bilgileri ilan etmek üzere bir internet sitesi açma zorunluluğu vardır." },
    { q: "Gizlilik sözleşmesi (NDA) önemi?", a: "Finansal verilerin ve ticari sırların korunması için danışmanlık süreçlerinde mutlaka imzalanmalıdır." },
    { q: "Vergi asistanı hata?", a: "Eğer yanlış bir bilgi verdiğimi düşünüyorsanız lütfen destek talebinde bulunun; mevzuat sürekli güncellenmektedir." },
    { q: "Daha fazla soru sormak istiyorum?", a: "Tabii ki, binden fazla mevzuat maddesini içeren kütüphaneme sorularınızı yöneltebilirsiniz." },
    { q: "İşten çıkarma maliyeti?", a: "Kıdem tazminatı, ihbar tazminatı ve kullanılmayan yıllık izin ücretlerinden oluşur; brüt ücret üzerinden hesaplanır." },
    { q: "İşe iade davası şartları?", a: "30 veya daha fazla işçi çalıştıran iş yerlerinde, en az 6 ay kıdemi olan işçilerin belirsiz süreli sözleşmelerinde geçerlidir." },
    { q: "Ücret bordrosu imzalatma?", a: "Elektronik imza kullanılmıyorsa, işçinin her ay bordrosunu ıslak imza ile onaylaması veya banka dekontu ile tevsik edilmesi şarttır." },
    { q: "SGK iş kazası bildirimi?", a: "Kazanın olduğu tarihten itibaren en geç 3 iş günü içinde SGK'ya bildirilmesi zorunluluktur." },
    { q: "Uzaktan çalışma vergisi?", a: "Çalışana ödenen internet, yemek veya ekipman yardımlarının vergisel durumu sosyal güvenlik ve gelir vergisi kanunlarına tabidir." },

    // SON DALGA (200+ HEDEFİ)
    { q: "Tapu harcı oranları?", a: "Gayrimenkul devirlerinde alıcıdan %2 ve satıcıdan %2 olmak üzere toplam %4 oranında tapu harcı ödenir." },
    { q: "Emlak vergisi ne zaman ödenir?", a: "Mayıs ve Kasım aylarında olmak üzere iki eşit taksitte belediyelere ödenir." },
    { q: "Kira geliri (GMSI) istisnası?", a: "Konut kira gelirlerinde her yıl güncellenen bir istisna tutarı mevcuttur; bu tutarın altındaki gelirler beyan edilmez." },
    { q: "Veraset ve İntikal Vergisi?", a: "Miras veya karşılıksız intikal yoluyla elde edilen varlıklar üzerinden kademeli oranlarla alınan bir servet vergisidir." },
    { q: "Miras bırakılan borçlar?", a: "Mirasçılar mirası reddetmedikleri sürece, murisin vergi ve diğer borçlarından müteselsilen sorumludurlar." },
    { q: "KKM (Kur Korumalı Mevduat) vergisi?", a: "Şirketler için belirli dönemlerde KKM faiz ve kur farkı kazançlarına yönelik vergi istisnaları uygulanmıştır; güncel durum takibi kritiktir." },
    { q: "Melek yatırımcı vergi teşviği?", a: "Bireysel Katılım Yatırımcısı (BKY) lisansına sahip kişilerin, startup yatırımlarının %75'ini gelir vergisi matrahından düşebilmesidir." },
    { q: "Girişim sermayesi fonu ayırma?", a: "Kurumlar, belirli şartlarla karlarının bir kısmını girişim sermayesi fonu olarak ayırıp vergiden düşebilirler." },
    { q: "TÜBİTAK 1512 desteği?", a: "Genç girişimcilere yönelik teknoloji tabanlı iş fikirleri için verilen geri ödemesiz hibe desteğidir." },
    { q: "Karbon vergisi nedir?", a: "Sürdürülebilirlik kapsamında, karbon salınımı yüksek olan ürünlerin gümrükte veya üretimde ek vergiye tabi tutulması sürecidir." },
    { q: "Yeşil tahvil (Green Bond)?", a: "Çevresel projelerin finansmanı için ihraç edilen ve vergi avantajları sunabilen borçlanma araçlarıdır." },
    { q: "Kripto varlık beyanı?", a: "Yurtiçi borsalardaki işlemler ve elde edilen kazançların vergilendirilmesi taslak aşamasında olup yakından takip edilmelidir." },
    { q: "NFT satışı vergisi?", a: "Dijital eserlerin satışı süreklilik arz ediyorsa ticari kazanç, arızi ise değer artış kazancı olarak değerlendirilebilir." },
    { q: "Yurtdışı hisse senedi temettüsü?", a: "Yabancı borsalardan elde edilen temettüler, belirli bir tutarı aşması halinde yıllık gelir vergisi beyannamesi ile beyan edilmelidir." },
    { q: "VİOP kazançları stopajı?", a: "Bireysel yatırımcılar için %10, kurumlar için %0 gibi farklı vergilendirme rejimleri mevcuttur." },
    { q: "Altın ve gümüş vergisi?", a: "Banka nezdindeki kıymetli maden hesapları kambiyo vergisine veya stopaja tabi olabilir." },
    { q: "Şüpheli ticari alacak karşılığı?", a: "Dava veya icra merhalesine gelmiş alacaklar için ayrılan ve gider yazılabilen karşılık tutarıdır." },
    { q: "Değersiz alacak nedir?", a: "Tahsil imkanı tamamen ortadan kalkan ve muhasebe kayıtlarından silinen alacak kalemidir." },
    { q: "Vazgeçilen alacaklar?", a: "Borçlunun ödeme güçlüğü nedeniyle alacaklı tarafından vazgeçilen tutarın 3 yıl boyunca bir fon hesabında tutulabilmesidir." },
    { q: "Reeskont faiz oranları?", a: "Merkez Bankası tarafından belirlenen ve dönem sonu alacak/borç değerlemelerinde kullanılan oranlardır." },
    { q: "Kasa fazlası tehlikesi?", a: "Kasada görünen ancak fiilen olmayan paranın ortaklara kullandırıldığı varsayımı ile adat faizi hesaplanması gerekebilir." },
    { q: "Ortaklardan alacaklara adat faizi?", a: "Şirket ortaklarının şirketten para çekmesi durumunda, emsallere uygun faiz işletilip KDV hesaplanması zorunluluğudur." },
    { q: "Örtülü kazanç dağıtımı?", a: "Emsallerinden bariz farklı fiyatlarla ortaklara menfaat sağlanmasıdır; ciddi vergi cezaları doğurur." },
    { q: "Bağımsız denetim sınırı 2024?", a: "Aktif toplamı, ciro ve çalışan sayısı kriterlerinden en az ikisini iki yıl üst üste aşan şirketler kapsam dadır." },
    { q: "Kamu yararını ilgilendiren kuruluşlar (KAYİK)?", a: "Halka açık şirketler, bankalar ve sigorta şirketleri gibi çok daha sıkı denetime tabi olan yapılardır." },
    { q: "İç kontrol sistemi faydaları?", a: "Şirket varlıklarının korunması, hataların önlenmesi ve operasyonel verimliliğin artırılması için kurulan mekanizmadır." },
    { q: "Yolsuzluk denetimi (Fraud Audit)?", a: "İşletme içindeki kasıtlı suistimallerin ve hilelerin tespiti için yapılan özel uzmanlık gerektiren denetimdir." },
    { q: "Stok sayım farkları muhasebesi?", a: "Fiili sayım ile kayıtlar arasındaki farkların nedenine göre (fire, hırsızlık vb.) vergi ve muhasebe açısından düzeltilmesidir." },
    { q: "Fire oranları rehberi?", a: "Ticaret odaları tarafından her sektör için belirlenen ve normal kabul edilen kayıp oranlarıdır." },
    { q: "Kur farkı faturaları?", a: "Vade farkı niteliğindeki kur artışları için düzenlenen ve KDV'ye tabi olan faturalardır." },
    { q: "Yıl içi vergi dairesi nakli?", a: "Adress değişikliği tescili ile birlikte beyannamelerin verildiği vergi dairesinin değişmesi sürecidir." },
    { q: "Matrah artırımı taksit ödemesi?", a: "Vergi barışı kapsamında yapılan başvuruların ödeme vadelerinin aksatılması hakkın yanmasına neden olabilir." },
    { q: "Yatırım izleme ve koordinasyon?", a: "Büyük ölçekli yatırımların yerel ve merkezi yönetimlerle uyum içinde yürütülmesini sağlayan kurumsal süreçtir." },
    { q: "Elite Strategy güvenilir mi?", a: "Kesinlikle! Profesyonel kadromuz ve ileri teknoloji çözümlerimizle sektörde referans kabul edilen mali bir gücüz." },
    { q: "Size nasıl güvenebilirim?", a: "Şeffaf raporlama, uluslararası standartlara uyum ve yüzlerce başarılı kurumsal referansımız güvenimizin teminatıdır." }
];

window.knowledgeBase = knowledgeBase;
